### PR TITLE
fix(VoiceConnection): disconnect method now actually disconnects

### LINKED ISSUE #138: I use the connection.disconnect() feature but it stays in VC.
**My bot is in VC. I try to disconnect it when there is no song playing. It doesn't leave or give an error.**

```js
const { getVoiceConnection } = require('@discordjs/voice');
const { MessageEmbed } = require('discord.js');

module.exports.run = async (bot, message, args, queue) => {
    if (!message.member.voice.channel) return message.channel.send({ content: `What? Excuse me? Do you really expect me to execute a MUSIC command without you being in a voice channel? Like how you gonna use them if you can't hear them bruh? Big brain much?` });

    if (queue === undefined) {
        const connection = getVoiceConnection(message.guild.id)
        connection.disconnect()
        message.channel.send({
            embeds: [new MessageEmbed()
                .setDescription("Thanks for tuning in!")
                .setColor("RED")
            ]
        })
        message.react("✅")
    } else {
        bot.distube.stop(message)
        message.react("✅")
        queue.voice.leave()
        message.channel.send({
            embeds: [new MessageEmbed()
                .setDescription("Thanks for tuning in!")
                .setColor("RED")
            ]
        })
    }
};
module.exports.config = {
    name: "disconnect",
    aliases: ["dc"]
}
```

**Further details:**

- @discordjs/voice version: 0.5.0
- Node.js version:14.17.1
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: not really at the top but is inconvinient.

**Relevant client options:**

- partials: none
- gateway intents: all
- other: none

### PR DESCRIPTION
**Pull request by amishshah**
**Please describe the changes this PR makes and why it should be merged:**

Resolves #138.

Calling `VoiceConnection#disconnect()` didn't actually send the correct voice state update packet to Discord. This has been fixed to null the channelId before sending the packet, and a test exposing this has been added.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes

### CODE REVIEW

File: src/VoiceConnection.ts [hunk 1]
```diff
@@ -499,6 +499,7 @@ export class VoiceConnection extends TypedEmitter<VoiceConnectionEvents> {
 		) {
 			return false;
 		}
+		Object.assign(this.joinConfig, { channelId: null });
```
Comment (kyranet) [inline src/VoiceConnection.ts:502]: Can't you just assign this? Like `this.joinConfig.channelId = null;`

**Review by kyranet — CHANGES_REQUESTED** [review]

**Review by kyranet — APPROVED** [review]
