### PR TITLE
fix(Examples): destroy discord.js v12 adapter less readily

### LINKED ISSUE #153: Adapter destroying voiceConnection when client reconnects
**Please describe the problem you are having in as much detail as possible:**
VoiceConnection changes state to `destroyed` from `ready` in the middle of playback. Sometimes this occurs after 10 minutes of listening, Sometimes after hours. Yet to find a proper way of reproducing this issue.
image

**Include a reproducible code sample here, if possible:**

```ts
    public async join(
        channel: Discord.VoiceChannel | Discord.StageChannel
    ): Promise<VoiceConnection | null> {
        try {
            this.voiceChannel = channel;
            const connection: VoiceConnection =
                getVoiceConnection(this.guild.id) ??
                joinVoiceChannel({
                    channelId: channel.id,
                    guildId: this.guild.id,
                    //@ts-ignore
                    adapterCreator: createDiscordJSAdapter(channel),
                    debug: this.client.config.debug.voiceConnection
                });
            this.connection = connection;
            this.connection
                .once("error", err => {
                    this.connection = null;
                    this.emit("error", err);
                })
                .on("stateChange", async (oldState, newState) => 
                    console.log(`oldStatus: ${oldState.status}, newStatus: ${newState.status}`)
                )
                .on("debug", console.log);
            return (
                (await entersState(connection, VoiceConnectionStatus.Ready, 15e3).catch(e => {
                    console.error(e);
                    if (connection.state.status !== "destroyed") connection.destroy();
                    if (this.exists) this._timeout();
                })) || null
            );
        } catch (error) {
            this.client.player.delete(channel.guild?.id as string);
            console.log("failed to obtain a voiceConnection");
            console.error(error);
            this.textChannel?.send(this.client.messages.error + error.toString());
            return null;
        }
    }
```

**Further details:**

- @discordjs/voice version: 0.5.4
- Node.js version: 14.15.0
- Operating system: Ubuntu 20.04 (also occurs on windows 10 with older versions of djs/voice)
- Priority this issue should have – please be realistic and elaborate if possible: medium to high. It really does mess with playback when occurring in the middle of playing.

**Relevant client options:**

- partials: none
- gateway intents: GUILDS, GUILD_VOICE_STATES, GUILD_MESSAGES
- other: none

### PR DESCRIPTION
**Pull request by amishshah**
**Please describe the changes this PR makes and why it should be merged:**

Adjusts the discord.js v12 adapter to match the same destroy conditions given by the adapter provided with discord.js v13.

Resolves #153 

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes

### CODE REVIEW

File: examples/basic/adapter.ts [hunk 1]
```diff
@@ -20,27 +20,24 @@ function trackClient(client: Client) {
...
-			adapters.get(guildId)?.destroy();
+	client.on(Constants.Events.SHARD_DISCONNECT, (_, shardID) => {
+		const guilds = trackedShards.get(shardID);
+		if (guilds) {
+			for (const guildId of guilds.values()) {
+				adapters.get(guildId)?.destroy();
+			}
 		}
-	}
+		trackedShards.set(shardID, new Set());
```
Comment (SpaceEEC) [inline examples/basic/adapter.ts:30]: Why not delete the set instead of replacing it?

**Review by SpaceEEC — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

File: examples/basic/adapter.ts [hunk 2]
```diff
@@ -20,27 +20,24 @@ function trackClient(client: Client) {
...
-}
-
-const trackedGuilds = new Map<WebSocketShard, Set<Snowflake>>();
-
-function cleanupGuilds(shard: WebSocketShard) {
-	const guilds = trackedGuilds.get(shard);
-	if (guilds) {
-		for (const guildId of guilds.values()) {
-			adapters.get(guildId)?.destroy();
+	client.on(Constants.Events.SHARD_DISCONNECT, (_, shardID) => {
```
Comment (kyranet) [inline examples/basic/adapter.ts:23]: If you're going to call the guild's ID with `Id` (see line 26), then change this to `shardId`, otherwise rename the variable below to `guildID`.

**Review by kyranet — CHANGES_REQUESTED** [review]

**Review by kyranet — APPROVED** [review]
